name = "rok-services"
compatibility_date = "2024-07-24"
pages_build_output_dir = ".next"

[env.production]
compatibility_date = "2024-07-24"

[[env.production.vars]]
# Environment variables will be set via Cloudflare Pages dashboard